string db_id # The ID of the custom landmark in MongoDB
string name # The name of the custom landmark, which can be used to ID the landmark if db_id is not provided.
bool is_tabletop # True if tabletop scene, which is faster.
---
code_it_msgs/Landmark[] landmarks
string error # Set to indicate that the primitive did not complete.
---
